version: "2"

services:
  acidfront:
    container_name: acidfront
    build:
      context: .
      dockerfile: Dockerfile-prd
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.backend=acidfrontprd"
      - "traefik.frontend.rule=PathPrefixStrip: /"
    networks:
      - traefik
networks:
  traefik:
    external:
      name: acidloadb_webgateway
